version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./.docker-compose/start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/var/www/app
  db:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=root
      - POSTGRES_DB=forte_central
    ports:
      - '5440:5432'
    tmpfs:
      - /var/lib/postgresql/data
